spring:
  profiles:

  # Jpa config
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          batch_size: 50
          fetch_size: 50
          lob:
            non_contextual_creation: true
        generate_statistics: true
        show_sql: true
        format_sql: true
        use_sql_comments: true


  # Datasource config
  datasource:
    url: jdbc:h2:mem:test
    username: postgres
    password: postgres
    data: 'classpath:/db/data.sql'

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 9000

logging:
  config: classpath:logback.xml

---
spring:
  profiles: test

  datasource:
    url: 'jdbc:h2:mem:test'
    username: 'postgres'
    password: 'postgres'
    data: 'classpath:/db/data.sql'

---
spring:
  profiles: dev

  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    url: 'jdbc:h2:mem:test'
    username: 'postgres'
    password: 'postgres'
    data: 'classpath:/db/data.sql'